### PR TITLE
HTTPSify everything (where possible)

### PR DESCRIPTION
**Pull request by wagnerand**
also, fixed a wrong link (jenkins-ci.org -> openstack.org
and made some absolute urls relative

### CODE REVIEW

**Comment by arlimus** [comment]
Thank you so much for these fixes! :)

I'll have fix the absolute URLs in the site-generator as well, so this doesn't come up again.

**Comment by wagnerand** [comment]
Thanks for the fast merge!

**Comment by wagnerand** [comment]
Yay, no more mixed content warnings in browsers!

**Comment by arlimus** [comment]
Nice! :D

**Pull request merged**
